---
- name: Install libguestfs-tools and libvirtd packages
  become: yes
  package:
    name:
      - git
      - libguestfs-tools
      - libvirt
      - libguestfs-xfs
      - gcc
      - python3-libguestfs
    state: latest

- name: Start libvirtd service
  service:
      name: "{{ item }}"
      state: started
      enabled: yes
  loop:
    - libvirtd

- name: Download image
  get_url:
    url: "{{ image_url }}"
    dest: "{{ downloaded_image_path }}"

- name: Creating a disk image for a new VM
  shell: qemu-img create -f qcow2 {{ tmp_image_path }} 20G
 
- name: Resizing file system
  shell: "virt-resize --expand /dev/sda1 {{ downloaded_image_path }} {{ tmp_image_path }}"

  #For some reason ssh service was failing to start in ubuntu 20.04. Reinstalling ssh service fixes the issue.
- name: Modifying ssh installation
  vkhitrin.libguestfs.guestfs_command:
    image: "{{ tmp_image_path }}"
    shell: "apt-get purge openssh-server -y && apt-get install openssh-server -y"

- name: Create user stack
  vkhitrin.libguestfs.guestfs_command:
    image: "{{ tmp_image_path }}"
    shell: "useradd -s /bin/bash -d /opt/stack -m stack"
  
- name: Add user stack to sudoers
  shell: "virt-customize -a {{ tmp_image_path }} --run-command 'echo \"stack ALL=(ALL) NOPASSWD: ALL\" | tee /etc/sudoers.d/stack '"
  
- name: Set password 'stack' for user 'stack'
  vkhitrin.libguestfs.guestfs_command:
    image: "{{ tmp_image_path }}"
    shell: 'echo "stack:stack" | chpasswd'

- name: Injecting ssh key for user 'stack'
  shell: virt-customize -a {{ tmp_image_path }} --ssh-inject stack:file:$HOME/.ssh/id_rsa.pub

- name: Setting hostname
  shell: virt-customize -a {{ tmp_image_path }} --hostname {{ libvirt_vm_name }}

  # For some reason the resizing of file systems (see above) breaks image boot. This step fixes VM boot.
- name: Updating grub in the VM image
  vkhitrin.libguestfs.guestfs_command:
    image: "{{ tmp_image_path }}"
    shell: "grub-install /dev/sda"

- name: Prepare the network file
  template:  
    src: 50-network.yaml.j2
    dest: /tmp/50-network.yaml

- name: Set network interfaces
  vkhitrin.libguestfs.guestfs_copy_in:
    image: "{{ tmp_image_path }}"
    src: /tmp/50-network.yaml
    dest: /etc/netplan/

- name: Copy the image file to /var/lib/libvirt/images
  become: yes
  copy:
    src: "{{ tmp_image_path }}"
    dest:  "/var/lib/libvirt/images/{{ libvirt_vm_name }}.qcow2"

- name: Remove temp files
  become: yes
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - "{{ tmp_image_path }}"
    - "{{ downloaded_image_path }}"

- name: Look for the image OS for optimzation
  shell: osinfo-query os |grep -q {{ image_os }}
  register: osinfo
  failed_when: osinfo.rc == 2

- name: Add OS variant to virt-install
  set_fact:
    install_params: "{{ (osinfo.rc ==0) | ternary('--os-variant ' + image_os , '')}}"

- name: Starting VM
  become: yes
  shell: virt-install {{ install_params }} --ram {{ libvirt_vm_memory_mb }} --vcpus {{ libvirt_vm_vcpus }} --disk path=/var/lib/libvirt/images/{{ libvirt_vm_name }}.qcow2,device=disk,bus=virtio,format=qcow2 --import --noautoconsole --vnc --network network:default --name {{ libvirt_vm_name }}

- name: Get host
  become: yes
  become_method: sudo
  shell: virsh domifaddr {{ libvirt_vm_name }} | awk '/ipv4/{print $4}' | cut -d'/' -f1
  register: devstack_ip_result
  retries: 10
  delay: 15
  until:
    - devstack_ip_result.rc == 0
    - devstack_ip_result.stdout != ''

- set_fact:
    devstack_ip: "{{ devstack_ip_result.stdout }}"

- name: Print {{ libvirt_vm_name }} IP
  debug:
    msg: "{{ libvirt_vm_name }} IP: {{ devstack_ip }}"

- name: Adding devstack to inventory
  lineinfile:
    path: hosts
    line: "{{libvirt_vm_name}} ansible_ssh_host={{ devstack_ip }} ansible_ssh_user=stack ansible_ssh_password=stack"
    state: present

- meta: refresh_inventory

- name: Reload service libvirtd to update dnsmasq
  become: yes
  systemd:
    name: libvirtd
    state: reloaded

- name: Add host to /etc/hosts
  become: yes
  lineinfile:
    path: /etc/hosts
    state: present
    regexp: "{{ libvirt_vm_name }}"
    line: "{{ hostvars[libvirt_vm_name]['ansible_ssh_host']}} {{ libvirt_vm_name }}"
